// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

// ApplicationError represents an application-level error that occurred during request processing.
type ApplicationError struct {
	// The error code indicating the type of application error that occurred.
	Code ApplicationErrorCode `json:"code"`
	// A human-readable message describing the application error.
	Message string `json:"message"`
}

// InternalServerError represents an internal server error that occurred during request processing.
type InternalServerError struct {
	// A human-readable message describing the internal server error.
	Message string `json:"message"`
}

type Query struct {
}

// ValidationError represents a validation error that occurred during input validation.
type ValidationError struct {
	// The validation error code indicating the type of validation failure.
	Code ValidationErrorCode `json:"code"`
	// An array of field paths indicating which fields failed validation.
	// For nested fields, each path segment is an element in the array.
	Field []string `json:"field"`
	// A human-readable message describing the validation error.
	Message string `json:"message"`
}

// ApplicationErrorCode enumerates the possible types of application errors.
type ApplicationErrorCode string

const (
	// Indicates the requested resource was not found.
	ApplicationErrorCodeNotFound ApplicationErrorCode = "NOT_FOUND"
	// Indicates the caller is not authorized to perform the requested operation.
	ApplicationErrorCodeUnauthorized ApplicationErrorCode = "UNAUTHORIZED"
	// Indicates the caller provided invalid input.
	ApplicationErrorCodeBadRequest ApplicationErrorCode = "BAD_REQUEST"
	// Indicates the caller does not have permission to perform the requested operation.
	ApplicationErrorCodeForbidden ApplicationErrorCode = "FORBIDDEN"
)

var AllApplicationErrorCode = []ApplicationErrorCode{
	ApplicationErrorCodeNotFound,
	ApplicationErrorCodeUnauthorized,
	ApplicationErrorCodeBadRequest,
	ApplicationErrorCodeForbidden,
}

func (e ApplicationErrorCode) IsValid() bool {
	switch e {
	case ApplicationErrorCodeNotFound, ApplicationErrorCodeUnauthorized, ApplicationErrorCodeBadRequest, ApplicationErrorCodeForbidden:
		return true
	}
	return false
}

func (e ApplicationErrorCode) String() string {
	return string(e)
}

func (e *ApplicationErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ApplicationErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ApplicationErrorCode", str)
	}
	return nil
}

func (e ApplicationErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ApplicationErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ApplicationErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// InternalServerErrorCode enumerates the possible types of internal server errors.
type InternalServerErrorCode string

const (
	// Indicates an unknown internal server error occurred.
	InternalServerErrorCodeUnknown InternalServerErrorCode = "UNKNOWN"
	// Indicates the server timed out waiting for an action or request to complete.
	InternalServerErrorCodeServerTimedOut InternalServerErrorCode = "SERVER_TIMED_OUT"
)

var AllInternalServerErrorCode = []InternalServerErrorCode{
	InternalServerErrorCodeUnknown,
	InternalServerErrorCodeServerTimedOut,
}

func (e InternalServerErrorCode) IsValid() bool {
	switch e {
	case InternalServerErrorCodeUnknown, InternalServerErrorCodeServerTimedOut:
		return true
	}
	return false
}

func (e InternalServerErrorCode) String() string {
	return string(e)
}

func (e *InternalServerErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InternalServerErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InternalServerErrorCode", str)
	}
	return nil
}

func (e InternalServerErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InternalServerErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InternalServerErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// ValidationErrorCode enumerates the possible types of validation errors.
type ValidationErrorCode string

const (
	// Indicates a required field was missing or empty.
	ValidationErrorCodeRequired ValidationErrorCode = "REQUIRED"
	// Indicates a field's value was invalid according to validation rules.
	ValidationErrorCodeInvalid ValidationErrorCode = "INVALID"
)

var AllValidationErrorCode = []ValidationErrorCode{
	ValidationErrorCodeRequired,
	ValidationErrorCodeInvalid,
}

func (e ValidationErrorCode) IsValid() bool {
	switch e {
	case ValidationErrorCodeRequired, ValidationErrorCodeInvalid:
		return true
	}
	return false
}

func (e ValidationErrorCode) String() string {
	return string(e)
}

func (e *ValidationErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ValidationErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ValidationErrorCode", str)
	}
	return nil
}

func (e ValidationErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ValidationErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ValidationErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
