package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/hovanhoa/llmgateway/internal/model"
)

// CreateAPIKey is the resolver for the createApiKey field.
func (r *mutationResolver) CreateAPIKey(ctx context.Context, accountID string) (*model.APIKeySecret, error) {
	return r.createAPIKey(ctx, accountID)
}

// RevokeAPIKey is the resolver for the revokeApiKey field.
func (r *mutationResolver) RevokeAPIKey(ctx context.Context, id string) (bool, error) {
	return r.revokeAPIKey(ctx, id)
}

// UpdateAPIKeyQuota is the resolver for the updateApiKeyQuota field.
func (r *mutationResolver) UpdateAPIKeyQuota(ctx context.Context, id string, monthlyTokenBudget *int, clearMonthlyTokenBudget *bool) (*model.APIKey, error) {
	return r.updateAPIKeyQuota(ctx, id, monthlyTokenBudget, clearMonthlyTokenBudget)
}

// APIKeys is the resolver for the apiKeys field.
func (r *queryResolver) APIKeys(ctx context.Context, accountID string) ([]model.APIKey, error) {
	return r.listAPIKeys(ctx, accountID)
}
