package api

import (
	"context"

	"github.com/hovanhoa/llmgateway/internal/model"
	"github.com/hovanhoa/llmgateway/pkg/core/auth"
	"github.com/hovanhoa/llmgateway/pkg/core/errors"
)

// This file is hand-written and not regenerated by gqlgen. It centralizes
// the RBAC checks resolvers need, since GraphQL operations all share a
// single HTTP route and so can't be gated per-operation by HTTP middleware.
// AuthMiddleware/RequireAuth (wired ahead of /graphql in internal/http)
// already guarantee a principal is present by the time these run.

// currentPrincipal returns the authenticated principal for this request.
func currentPrincipal(ctx context.Context) *auth.Principal[model.Identity, model.Role] {
	return auth.GetPrincipal[model.Identity, model.Role](ctx)
}

// requireRole returns an error unless the current principal holds at least
// one of the given roles.
func requireRole(ctx context.Context, roles ...model.Role) error {
	principal := currentPrincipal(ctx)
	if principal == nil || !principal.HasRole(roles...) {
		return errors.New("forbidden: requires role %v", roles)
	}
	return nil
}

// requireSelfOrRole returns an error unless the current principal is
// accountID itself, or holds at least one of the given roles. Used for
// operations a user may always perform on their own account (e.g. issuing
// their own API key) but which require elevated privilege to perform on
// someone else's.
func requireSelfOrRole(ctx context.Context, accountID string, roles ...model.Role) error {
	principal := currentPrincipal(ctx)
	if principal != nil && principal.ID == accountID {
		return nil
	}
	return requireRole(ctx, roles...)
}
