package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/hovanhoa/llmgateway/internal/model"
)

// TeamRequestLogs is the resolver for the teamRequestLogs field.
func (r *queryResolver) TeamRequestLogs(ctx context.Context, teamID string, limit *int, offset *int) (*model.RequestLogConnection, error) {
	return r.teamRequestLogs(ctx, teamID, limit, offset)
}

// MyRequestLogs is the resolver for the myRequestLogs field.
func (r *queryResolver) MyRequestLogs(ctx context.Context, limit *int, offset *int) (*model.RequestLogConnection, error) {
	return r.myRequestLogs(ctx, limit, offset)
}

// GlobalRequestLogs is the resolver for the globalRequestLogs field.
func (r *queryResolver) GlobalRequestLogs(ctx context.Context, limit *int, offset *int) (*model.RequestLogConnection, error) {
	return r.globalRequestLogs(ctx, limit, offset)
}
