package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/hovanhoa/llmgateway/internal/model"
)

// CreateTeam is the resolver for the createTeam field.
func (r *mutationResolver) CreateTeam(ctx context.Context, name string) (*model.Team, error) {
	return r.createTeam(ctx, name)
}

// UpdateTeam is the resolver for the updateTeam field.
func (r *mutationResolver) UpdateTeam(ctx context.Context, id string, name string) (*model.Team, error) {
	return r.updateTeam(ctx, id, name)
}

// DeleteTeam is the resolver for the deleteTeam field.
func (r *mutationResolver) DeleteTeam(ctx context.Context, id string) (bool, error) {
	return r.deleteTeam(ctx, id)
}

// UpdateTeamModelAllowlist is the resolver for the updateTeamModelAllowlist field.
func (r *mutationResolver) UpdateTeamModelAllowlist(ctx context.Context, teamID string, allowlist []string) (*model.Team, error) {
	return r.updateTeamModelAllowlist(ctx, teamID, allowlist)
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context, limit *int, offset *int) (*model.TeamConnection, error) {
	return r.listTeams(ctx, limit, offset)
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, id string) (*model.Team, error) {
	return r.getTeam(ctx, id)
}

// IsModelAllowed is the resolver for the isModelAllowed field.
func (r *queryResolver) IsModelAllowed(ctx context.Context, teamID string, provider string, model string) (bool, error) {
	return r.isModelAllowed(ctx, teamID, provider, model)
}
