package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"time"

	"github.com/hovanhoa/llmgateway/internal/model"
)

// TeamUsage is the resolver for the teamUsage field.
func (r *queryResolver) TeamUsage(ctx context.Context, teamID string, since *time.Time) (*model.UsageSummary, error) {
	return r.teamUsage(ctx, teamID, since)
}
