package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"time"

	"github.com/hovanhoa/llmgateway/internal/model"
)

// TeamUsage is the resolver for the teamUsage field.
func (r *queryResolver) TeamUsage(ctx context.Context, teamID string, since *time.Time) (*model.UsageSummary, error) {
	return r.teamUsage(ctx, teamID, since)
}

// MyUsage is the resolver for the myUsage field.
func (r *queryResolver) MyUsage(ctx context.Context, since *time.Time) (*model.UsageSummary, error) {
	return r.myUsage(ctx, since)
}

// AccountUsage is the resolver for the accountUsage field.
func (r *queryResolver) AccountUsage(ctx context.Context, accountID string, since *time.Time) (*model.UsageSummary, error) {
	return r.accountUsage(ctx, accountID, since)
}

// TeamUsageByAccount is the resolver for the teamUsageByAccount field.
func (r *queryResolver) TeamUsageByAccount(ctx context.Context, teamID string, since *time.Time) ([]model.AccountUsage, error) {
	return r.teamUsageByAccount(ctx, teamID, since)
}

// TeamUsageByModel is the resolver for the teamUsageByModel field.
func (r *queryResolver) TeamUsageByModel(ctx context.Context, teamID string, since *time.Time) ([]model.ModelUsage, error) {
	return r.teamUsageByModel(ctx, teamID, since)
}

// TeamUsageDaily is the resolver for the teamUsageDaily field.
func (r *queryResolver) TeamUsageDaily(ctx context.Context, teamID string, since *time.Time, until *time.Time) ([]model.DailyUsage, error) {
	return r.teamUsageDaily(ctx, teamID, since, until)
}

// GlobalUsage is the resolver for the globalUsage field.
func (r *queryResolver) GlobalUsage(ctx context.Context, since *time.Time) (*model.UsageSummary, error) {
	return r.globalUsage(ctx, since)
}

// GlobalUsageByTeam is the resolver for the globalUsageByTeam field.
func (r *queryResolver) GlobalUsageByTeam(ctx context.Context, since *time.Time) ([]model.TeamUsage, error) {
	return r.globalUsageByTeam(ctx, since)
}
