package model

import "github.com/hovanhoa/llmgateway/pkg/core/auth"

// This file is hand-written and not regenerated by gqlgen. It defines the
// concrete type parameters used to instantiate the generic auth framework
// in pkg/core/auth for this project.

// Identity identifies the kind of principal making a request. There is
// currently only one kind of principal in this project: an Account
// authenticated by an API key or a session JWT.
type Identity string

const (
	// IdentityAccount identifies a principal authenticated as an Account,
	// via an API key or a session JWT.
	IdentityAccount Identity = "ACCOUNT"
)

// principalMetadataAPIKeyID is the auth.Principal.Metadata key under which
// the specific API key ID that authenticated a request is stashed - set
// only when the credential was an API key, never for a session JWT (which
// isn't tied to any one key). See internal/authz.Authorizer, which sets it,
// and internal/proxy's per-key quota enforcement, which reads it.
const principalMetadataAPIKeyID = "apiKeyId"

// WithAPIKeyID returns principal with its API key id set in Metadata.
func WithAPIKeyID(principal *auth.Principal[Identity, Role], apiKeyID string) *auth.Principal[Identity, Role] {
	if principal.Metadata == nil {
		principal.Metadata = map[string]interface{}{}
	}
	principal.Metadata[principalMetadataAPIKeyID] = apiKeyID
	return principal
}

// APIKeyIDFromPrincipal returns the API key ID that authenticated principal,
// if the credential used was an API key (as opposed to a session JWT).
func APIKeyIDFromPrincipal(principal *auth.Principal[Identity, Role]) (string, bool) {
	if principal == nil || principal.Metadata == nil {
		return "", false
	}
	id, ok := principal.Metadata[principalMetadataAPIKeyID].(string)
	return id, ok && id != ""
}
