package model

// This file is hand-written and not regenerated by gqlgen. It defines the
// concrete type parameters used to instantiate the generic auth framework
// in pkg/core/auth for this project.

// Identity identifies the kind of principal making a request. There is
// currently only one kind of principal in this project: an Account
// authenticated by its API key.
type Identity string

const (
	// IdentityAccount identifies a principal authenticated as an Account via
	// its API key.
	IdentityAccount Identity = "ACCOUNT"
)
