// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// Account represents a user account in the system
type Account struct {
	// Unique identifier for the account
	ID string `json:"id"`
	// Email of the account
	Email string `json:"email"`
	// Username of the account
	Username string `json:"username"`
	// Team this account belongs to, if any
	TeamID *string `json:"teamId,omitempty"`
	// Timestamp the account was created
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp the account was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// AccountConnection is a single page of accounts
type AccountConnection struct {
	// Accounts contained in this page
	Items []Account `json:"items"`
	// Total number of accounts matching the query, ignoring pagination
	TotalCount int `json:"totalCount"`
	// Whether a further page follows this one
	HasNextPage bool `json:"hasNextPage"`
}

// Team represents a team in the system
type Team struct {
	// Unique identifier for the team
	ID string `json:"id"`
	// Display name of the team
	Name string `json:"name"`
	// Timestamp the team was created
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp the team was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// TeamConnection is a single page of teams
type TeamConnection struct {
	// Teams contained in this page
	Items []Team `json:"items"`
	// Total number of teams matching the query, ignoring pagination
	TotalCount int `json:"totalCount"`
	// Whether a further page follows this one
	HasNextPage bool `json:"hasNextPage"`
}
