package model

import "strings"

// This file is hand-written and not regenerated by gqlgen.

// IsModelAllowed reports whether a provider/model pair is permitted by the
// team's ModelAllowlist. An empty allowlist means no restriction has been
// configured yet, so everything is allowed. Entries are "provider:model";
// a model of "*" matches any model for that provider.
func (t *Team) IsModelAllowed(provider string, model string) bool {
	if len(t.ModelAllowlist) == 0 {
		return true
	}

	for _, entry := range t.ModelAllowlist {
		entryProvider, entryModel, ok := strings.Cut(entry, ":")
		if !ok {
			continue
		}
		if entryProvider == provider && (entryModel == "*" || entryModel == model) {
			return true
		}
	}

	return false
}
