package model

import "time"

// This file is hand-written and not regenerated by gqlgen.

// UsageEvent is one durable, immutable record of a completed LLM proxy
// call, stored in the usage_event table. It is the source of truth
// aggregated into a UsageSummary for reporting.
type UsageEvent struct {
	ID               string
	RequestID        string
	AccountID        string
	TeamID           *string
	Provider         string
	Model            string
	PromptTokens     int
	CompletionTokens int
	TotalTokens      int
	CostUSD          float64
	CreatedAt        time.Time
}
