// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateNoteRequest struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type Mutation struct {
}

type Note struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Query struct {
}
