// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package client

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// CreateNoteCreateNote includes the requested fields of the GraphQL type Note.
type CreateNoteCreateNote struct {
	Id          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
}

// GetId returns CreateNoteCreateNote.Id, and is useful for accessing the field via an interface.
func (v *CreateNoteCreateNote) GetId() string { return v.Id }

// GetTitle returns CreateNoteCreateNote.Title, and is useful for accessing the field via an interface.
func (v *CreateNoteCreateNote) GetTitle() string { return v.Title }

// GetDescription returns CreateNoteCreateNote.Description, and is useful for accessing the field via an interface.
func (v *CreateNoteCreateNote) GetDescription() string { return v.Description }

// GetCreatedAt returns CreateNoteCreateNote.CreatedAt, and is useful for accessing the field via an interface.
func (v *CreateNoteCreateNote) GetCreatedAt() time.Time { return v.CreatedAt }

type CreateNoteRequest struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

// GetTitle returns CreateNoteRequest.Title, and is useful for accessing the field via an interface.
func (v *CreateNoteRequest) GetTitle() string { return v.Title }

// GetDescription returns CreateNoteRequest.Description, and is useful for accessing the field via an interface.
func (v *CreateNoteRequest) GetDescription() string { return v.Description }

// CreateNoteResponse is returned by CreateNote on success.
type CreateNoteResponse struct {
	CreateNote CreateNoteCreateNote `json:"createNote"`
}

// GetCreateNote returns CreateNoteResponse.CreateNote, and is useful for accessing the field via an interface.
func (v *CreateNoteResponse) GetCreateNote() CreateNoteCreateNote { return v.CreateNote }

// DeleteNoteByIdDeleteNote includes the requested fields of the GraphQL type Note.
type DeleteNoteByIdDeleteNote struct {
	Id          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
}

// GetId returns DeleteNoteByIdDeleteNote.Id, and is useful for accessing the field via an interface.
func (v *DeleteNoteByIdDeleteNote) GetId() string { return v.Id }

// GetTitle returns DeleteNoteByIdDeleteNote.Title, and is useful for accessing the field via an interface.
func (v *DeleteNoteByIdDeleteNote) GetTitle() string { return v.Title }

// GetDescription returns DeleteNoteByIdDeleteNote.Description, and is useful for accessing the field via an interface.
func (v *DeleteNoteByIdDeleteNote) GetDescription() string { return v.Description }

// GetCreatedAt returns DeleteNoteByIdDeleteNote.CreatedAt, and is useful for accessing the field via an interface.
func (v *DeleteNoteByIdDeleteNote) GetCreatedAt() time.Time { return v.CreatedAt }

// DeleteNoteByIdResponse is returned by DeleteNoteById on success.
type DeleteNoteByIdResponse struct {
	DeleteNote DeleteNoteByIdDeleteNote `json:"deleteNote"`
}

// GetDeleteNote returns DeleteNoteByIdResponse.DeleteNote, and is useful for accessing the field via an interface.
func (v *DeleteNoteByIdResponse) GetDeleteNote() DeleteNoteByIdDeleteNote { return v.DeleteNote }

// GetNoteByIdNote includes the requested fields of the GraphQL type Note.
type GetNoteByIdNote struct {
	Id          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
}

// GetId returns GetNoteByIdNote.Id, and is useful for accessing the field via an interface.
func (v *GetNoteByIdNote) GetId() string { return v.Id }

// GetTitle returns GetNoteByIdNote.Title, and is useful for accessing the field via an interface.
func (v *GetNoteByIdNote) GetTitle() string { return v.Title }

// GetDescription returns GetNoteByIdNote.Description, and is useful for accessing the field via an interface.
func (v *GetNoteByIdNote) GetDescription() string { return v.Description }

// GetCreatedAt returns GetNoteByIdNote.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetNoteByIdNote) GetCreatedAt() time.Time { return v.CreatedAt }

// GetNoteByIdResponse is returned by GetNoteById on success.
type GetNoteByIdResponse struct {
	Note GetNoteByIdNote `json:"note"`
}

// GetNote returns GetNoteByIdResponse.Note, and is useful for accessing the field via an interface.
func (v *GetNoteByIdResponse) GetNote() GetNoteByIdNote { return v.Note }

// GetNotesNotesNote includes the requested fields of the GraphQL type Note.
type GetNotesNotesNote struct {
	Id          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
}

// GetId returns GetNotesNotesNote.Id, and is useful for accessing the field via an interface.
func (v *GetNotesNotesNote) GetId() string { return v.Id }

// GetTitle returns GetNotesNotesNote.Title, and is useful for accessing the field via an interface.
func (v *GetNotesNotesNote) GetTitle() string { return v.Title }

// GetDescription returns GetNotesNotesNote.Description, and is useful for accessing the field via an interface.
func (v *GetNotesNotesNote) GetDescription() string { return v.Description }

// GetCreatedAt returns GetNotesNotesNote.CreatedAt, and is useful for accessing the field via an interface.
func (v *GetNotesNotesNote) GetCreatedAt() time.Time { return v.CreatedAt }

// GetNotesResponse is returned by GetNotes on success.
type GetNotesResponse struct {
	Notes []GetNotesNotesNote `json:"notes"`
}

// GetNotes returns GetNotesResponse.Notes, and is useful for accessing the field via an interface.
func (v *GetNotesResponse) GetNotes() []GetNotesNotesNote { return v.Notes }

// __CreateNoteInput is used internally by genqlient
type __CreateNoteInput struct {
	Input CreateNoteRequest `json:"input"`
}

// GetInput returns __CreateNoteInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateNoteInput) GetInput() CreateNoteRequest { return v.Input }

// __DeleteNoteByIdInput is used internally by genqlient
type __DeleteNoteByIdInput struct {
	Id string `json:"id"`
}

// GetId returns __DeleteNoteByIdInput.Id, and is useful for accessing the field via an interface.
func (v *__DeleteNoteByIdInput) GetId() string { return v.Id }

// __GetNoteByIdInput is used internally by genqlient
type __GetNoteByIdInput struct {
	Id string `json:"id"`
}

// GetId returns __GetNoteByIdInput.Id, and is useful for accessing the field via an interface.
func (v *__GetNoteByIdInput) GetId() string { return v.Id }

// The query or mutation executed by CreateNote.
const CreateNote_Operation = `
mutation CreateNote ($input: CreateNoteRequest!) {
	createNote(req: $input) {
		id
		title
		description
		createdAt
	}
}
`

func CreateNote(
	ctx_ context.Context,
	client_ graphql.Client,
	input CreateNoteRequest,
) (*CreateNoteResponse, error) {
	req_ := &graphql.Request{
		OpName: "CreateNote",
		Query:  CreateNote_Operation,
		Variables: &__CreateNoteInput{
			Input: input,
		},
	}
	var err_ error

	var data_ CreateNoteResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by DeleteNoteById.
const DeleteNoteById_Operation = `
mutation DeleteNoteById ($id: ID!) {
	deleteNote(id: $id) {
		id
		title
		description
		createdAt
	}
}
`

func DeleteNoteById(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (*DeleteNoteByIdResponse, error) {
	req_ := &graphql.Request{
		OpName: "DeleteNoteById",
		Query:  DeleteNoteById_Operation,
		Variables: &__DeleteNoteByIdInput{
			Id: id,
		},
	}
	var err_ error

	var data_ DeleteNoteByIdResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by GetNoteById.
const GetNoteById_Operation = `
query GetNoteById ($id: ID!) {
	note(id: $id) {
		id
		title
		description
		createdAt
	}
}
`

func GetNoteById(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (*GetNoteByIdResponse, error) {
	req_ := &graphql.Request{
		OpName: "GetNoteById",
		Query:  GetNoteById_Operation,
		Variables: &__GetNoteByIdInput{
			Id: id,
		},
	}
	var err_ error

	var data_ GetNoteByIdResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by GetNotes.
const GetNotes_Operation = `
query GetNotes {
	notes {
		id
		title
		description
		createdAt
	}
}
`

func GetNotes(
	ctx_ context.Context,
	client_ graphql.Client,
) (*GetNotesResponse, error) {
	req_ := &graphql.Request{
		OpName: "GetNotes",
		Query:  GetNotes_Operation,
	}
	var err_ error

	var data_ GetNotesResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
